# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(946, 700)
        MainWindow.setMinimumSize(QtCore.QSize(946, 700))
        MainWindow.setMaximumSize(QtCore.QSize(946, 700))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_copy = QtWidgets.QPushButton(self.centralwidget)
        self.btn_copy.setGeometry(QtCore.QRect(520, 630, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_copy.setFont(font)
        self.btn_copy.setObjectName("btn_copy")
        self.lb_image = QtWidgets.QLabel(self.centralwidget)
        self.lb_image.setGeometry(QtCore.QRect(50, 200, 411, 421))
        self.lb_image.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_image.setText("")
        self.lb_image.setObjectName("lb_image")
        self.lb_result = QtWidgets.QLabel(self.centralwidget)
        self.lb_result.setGeometry(QtCore.QRect(520, 50, 361, 571))
        self.lb_result.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_result.setObjectName("lb_result")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(120, 50, 221, 51))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cb_type = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.cb_type.setFont(font)
        self.cb_type.setObjectName("cb_type")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.horizontalLayout.addWidget(self.cb_type)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(50, 120, 411, 51))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.edit_file = QtWidgets.QLineEdit(self.widget1)
        self.edit_file.setReadOnly(True)
        self.edit_file.setObjectName("edit_file")
        self.horizontalLayout_2.addWidget(self.edit_file)
        self.btn_select = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn_select.setFont(font)
        self.btn_select.setObjectName("btn_select")
        self.horizontalLayout_2.addWidget(self.btn_select)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AI图像识别工具"))
        self.btn_copy.setText(_translate("MainWindow", "复制到剪切板"))
        self.lb_result.setText(_translate("MainWindow", "显示识别结果"))
        self.label.setText(_translate("MainWindow", "选择识别类型"))
        self.cb_type.setItemText(0, _translate("MainWindow", "银行卡"))
        self.cb_type.setItemText(1, _translate("MainWindow", "植物"))
        self.cb_type.setItemText(2, _translate("MainWindow", "动物"))
        self.cb_type.setItemText(3, _translate("MainWindow", "通用票据"))
        self.cb_type.setItemText(4, _translate("MainWindow", "营业执照"))
        self.cb_type.setItemText(5, _translate("MainWindow", "身份证"))
        self.cb_type.setItemText(6, _translate("MainWindow", "车牌号"))
        self.cb_type.setItemText(7, _translate("MainWindow", "驾驶证"))
        self.cb_type.setItemText(8, _translate("MainWindow", "行驶证"))
        self.cb_type.setItemText(9, _translate("MainWindow", "车型"))
        self.cb_type.setItemText(10, _translate("MainWindow", "Logo"))
        self.label_2.setText(_translate("MainWindow", "选择要识别的图片"))
        self.btn_select.setText(_translate("MainWindow", "选择"))

